### ISSUE TITLE
Questions about ReservationTable.cpp

### ISSUE THREAD

**Issue by RigCor7** [Jiaoyang-Li/MAPF-LNS2#4]
I saw that the code on line 200 mentioned that (location < constraint_table.map_size) is vertex conflict, and other situations are edge conflict. But in theory, any location is smaller than the map size. For example, for a 32x32 map, the maximum location is 31\*32+31, which is smaller than 32*32. Can you give an edge conflict situation? Thank you.

**Comment by Jiaoyang-Li** [comment]
This is because we convert an edge (u,v) into a number by (1 + u) * map_size + v so that the constraint table can maintain both vertex constraints and edge constraints. More details can be found here:
https://github.com/Jiaoyang-Li/MAPF-LNS2/blob/a7906874f9f32e6e74fa187455b3764d792004cd/inc/ConstraintTable.h#L66C2-L66C18

**Comment by RigCor7** [comment]
Thanks a lot!
